### ISSUE TITLE
Quoting service adding ACCEPT header with PUT calls to payerfsp

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#1066]
**Summary**:
As per the API spec doc, the final response to payerfsp should not contain ACCEPT header. But in the PUT /quotes to payerfsp, I see ACCEPT header is coming though the payeefsp is not sending the same.

**Severity**:
HIGH
**Priority**:
Medium

**Expected Behavior**

The final response (PUT calls from switch to FSP) should not contain ACCEPT header.

**Steps to Reproduce**
  1. Send POST /quotes from postman from P2P golden path
  2. Observe the final response at payerfsp callbacks that has ACCEPT header
  **Note:**  This is when using Mojaloop-simulators. With old sims, you won't see this issue because the old sims stripping this header from switch.

**Pull Requests**
- [x] https://github.com/mojaloop/quoting-service/pull/86
- [x] https://github.com/mojaloop/central-ledger/pull/481 <-- not a fix, but adds value for dev purposes

**Specifications**
  - Component (if known): Quoting service
  - Version: helm 8.4.0
  - Platform: Mac OS
  - Subsystem: Mojaloop
  - Type of testing: Contract / API 
  - Bug found/raised by: Sri

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by elnyry** [comment]
Issue accepted, moving to repro and further steps..

**Comment by ggrg** [comment]
@sri-miriyala, @elnyry, please make sure you've read the PR Notes [here](https://github.com/mojaloop/quoting-service/pull/86#issue-342924079).

**Comment by ggrg** [comment]
## Notes
While the PR is quite simplistic in fixing the issue it took great effort to identify it as I was not using the mojaloop-simulator. The story itself has stated I shouldn't use mojaloop/simulator, but hasn't provided the PUT request from mojaloop-simulator to the quoting-service, so I tried to reproduce with Postman.
1. Initially, I tried providing `Accept:application/vnd.interoperability.quotes+json;version=1.0` for `PUT /quotes/{id}` which resulted in FSPIOPError added 3 mo ago and handling it, but this attempt was not resulting in reproducing the issue.
2. Then, I tried removing the HTTP Accept header from the Postman call and surprisingly it again did not result in repro, but rather in another non-expected FSPIOPError with description `Malformed syntax - Invalid accept header`. This is where my quest has begun and I needed to investigate:
  a. **Q**: Why the request is not being accepted? **A**: HTTP Accept header with value `*/*` was present
  b. **Q**: Is this value getting set by Hapi or Hapi plugins? **A**: No.
  c . **Q**: Is this value getting set by node internals? **A**: No.
  d. **Q**: Is this value set by Postman? **A**: Yes.
  e. **Q**: Can it be disabled? **A**: No.
  f. **Q**: May another tool be used for sending the request? **A**: No. Unfortunately shell commands were also adding it, incl. curl, wget.
  g. **Q**: Why is this happening? **A**: According to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.3.2) - _A request without any Accept header field implies that the user agent will accept any media type in response._ **What a surprise!?**
  h. **Q**: How in this case, regression tests for transfers and quotes were functioning? **A**: First, we have some tests that send Accept headers that need to be fixed and second - surprisingly Node was able to send PUT request without defaulting missing header as `Accept: */*`.
3. This is where I eventually exported the Postman `PUT /quotes/{id}` request as **NodeJS/Request** and executed the script via node. The result was that I was finally able to reproduce the issue after the request was not rejected onPreRequest Hapi validation, and that resulted in the proposed herein fix.

## Outcome
1. Bug reports related to PUT calls, send by simulators in future MUST include the actual request, in order to facilitate reproduction;
2. Test collections for Regression testing need to be revised for PUT calls and Accept header should be removed where present;
3. We might soon need to provision for `Accept: */*` header in the shared library file: [@mojaloop/central-services-shared/src/util/headerValidation/index.js:55](https://github.com/mojaloop/central-services-shared/blob/v8.4.3/src/util/headerValidation/index.js#L55)
