### ISSUE TITLE
Quality testing Scenarios

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#116]
Quality testing Scenarios

**Comment by kjw000** [comment]
@bhcrosslake do you have an estimated story points for this?

**Comment by kjw000** [comment]
Moving to the next sprint since Bill is off on another project this week.  Most likely this will become a document to augment development work.  
-Need to have unit tests for each of the code that is checked in at a minimum.
-SonarQube code coverage will be run.  (do we run on dev or just the master branch).
-Threat Modeling defined in 1.3 or 1.4.

**Comment by elnyry** [comment]
Kim for #2, Bill suggested we do Code coverage for only master branch, so thats how the current CI configurationis.

**Comment by elnyry** [comment]
Too vague, need specific items.

Please re-open when there's more clarity. Moreover, this is covered as part of numerous other stories.
