### ISSUE TITLE
Review Overall Mojaloop Security Architecture 

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1227]
## **Goal**:
As an "OSS Developer" I want to ensure that identity and authentication issues are well addressed as the architecture involves.

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@pedrosousabarreto please provide more clarity on this. Feel free to break down into different issues if needed.

**Comment by pedrosousabarreto** [comment]
My proposal for security focus areas:
* Switch
    * intra switch security
        * how services authenticate and authorise when talking to each other 
    * inter switch security (multiple switches scenario)
        * how multiple switches  authenticate and authorise when talking to each other 
    * message topics and database authorisation
    * operator authorisation and authentication (identity management)
    * mechanisms for key/secret generation, storage, verification and invalidation
        * ideally these should be pluggable with a standard provided implementation
* switch<->FSP security
    * how to secure FSPs authenticate and authorise when talking to each other

**Comment by pedrosousabarreto** [comment]
Tentative approach to be:
- Propose standard recommendations and eventual implementations for the main security concerns below.

Updated/reworked areas:
* Switch
    * intra switch security
        * how services authenticate and authorise when talking to each other 
    * inter switch security (multiple switches scenario)
        * how multiple switches  authenticate and authorise when talking to each other 
    * operator authorisation and authentication (identity management)
* Switch infrastructure
    * message topics and database authorisation
    * platform secrets (cluster)
    * gateway secrets
* switch<->FSP security
    * how to secure FSPs authenticate and authorise when talking to each other
    * callbacks from the switch (pain point)
* mechanisms for key/secret generation, storage, verification and invalidation
    * ideally these should be pluggable with a standard provided implementation

**Comment by elnyry** [comment]
Thanks Pedro. Following-up on our earlier call/discussion, here are a few notes from my side.

1. I think inter-switch Security can be considered out-of-scope for now because there hasn't been a Use Case brought up, that involves inter-Switch security. In any case, why wouldn't it fall under Switch <-> FSP Security?
2. Switch <-> FSP Security. I think for this (we already agreed on the call that we do not need to re-invent this) we need to build on the work done in the Specification set already (here: https://github.com/mojaloop/mojaloop-specification/tree/master/documents). The three documents here, [PKI Best Practices](https://github.com/mojaloop/mojaloop-specification/blob/master/documents/PKI%20Best%20Practices.md), [Signature](https://github.com/mojaloop/mojaloop-specification/blob/master/documents/Signature.md) and [Encryption](https://github.com/mojaloop/mojaloop-specification/blob/master/documents/Encryption.md) cover some aspects, so I think we can build on those, unless you feel they are insufficient, in which case, feedback on those is welcome.
3. However, **Operator Security** and **Intra-switch security** (in my opinion, 2.1 'message topics and DB auth also fall under 1.2 - intra Switch security) are two areas that are interesting to me; more-so because there isn't much work on these topics in the Mojaloop OSS space, so I would encourage prioritizing those two aspects.

**Comment by godfreykutumela** [comment]
Hi @pedrosousabarreto can you please provide closing remarks to this story based on my response to @elnyry so that we can close by end of the week if possible.

**Comment by elnyry** [comment]
@godfreykutumela regarding this
>@elnyry @pedrosousabarreto I think Inter-switch scope is limited to communications between various services within the switch itself and calls to the FSP's are not included hence it is separate from Switch < > FSP

I think the communications between various services within the switch falls under 'Intra-Switch Security', which I addressed in my point#3 in the comment. So, my comment on inter-switch scope still stands..

**Comment by godfreykutumela** [comment]
Apologies @elnyry actually I wanted to say intra-switch in my comment

**Comment by godfreykutumela** [comment]
I suggest we prioritize on **Operator Security and Intra-switch security** and it will be great if we can further break it down to 2 or 3 sub-topics max to make more specific and ease measure the effort required to complete it preferably within the next PI. @lewisdaly @elnyry @pedrosousabarreto @rasputtintin

**Comment by elnyry** [comment]
Sounds good, thank @godfreykutumela..

**Comment by pedrosousabarreto** [comment]
@elnyry and @godfreykutumela 
My suggestion is that keep all the focus areas above and:
- For all areas we at least provide a guideline how to address them;
- For Intra-switch, switch-FSP, operator and infrastructure we work on providing not only the guideline by also a reference implementation as part of the opensource solution.

For things like HSM, we should implement a bridge and adapter architecture. So that internal services consume security functionality from an internal service, provided with the open source solution, which in turn can implement several adapters for each external interface (for example talking to a specific HSM implementation or standard).
