### ISSUE TITLE
FSP not found error not showing up

### ISSUE THREAD

**Issue by IvtVasquez** [mojaloop/project#1259]
**Summary**:
When try sending a GET /parties request on a FSP that is not registered in switch, getting an unknown error with lots of extension list key value pairs.
Am receiving the error code "3201" error msg "Destination FSP does not exist or cannot be found" 

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
The expected error code on a FSP that is not registered in switch is "1001" error msg "Destination communication error - Failed to send HTTP request to host" 

**Steps to Reproduce**
1. Access the following request GET -partiesBy Type and ID --> Negative Test cases FSP not Found
2. Send the Get request > with FSP that is not registered in switch
3. Error code expected “"1001" error msg "Destination communication error - Failed to send HTTP request to host" 

**Specifications**
  - Component (if known): ALS
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
@Sridevi Miriyala @Iveth Vásquez 

General comments:

1. Please provide the version where this issue was found, otherwise whoever is trying to reproduce the issue will have to speculate on the version, which is not ideal
2. Please provide a “Bug found/raised by:” or a contact person to reach out for any questions regarding the bug
3. Lastly, it will help if you can provide the text - code for the request and responses, so that it makes triaging, reproduction of the bug easier

**Comment by elnyry** [comment]
Secondly and most importantly, this bug indicates that expected behavior on a `GET /parties` call for an FSP thats not registered should be:
```
"1001" error msg "Destination communication error - Failed to send HTTP request to host"
```

I have to disagree with this assertion.

Please consider this: If an FSP is registered and is unreachable based on the endpoints configured for that FSP, then a 1001 error is reasonable. However, if an FSP is not registered in the Switch, then why would we even try to communicate with it? 

In this case - error code "3201" error msg "Destination FSP does not exist or cannot be found" seems perfectly perfected to this scenario in my opinion.

Please let me know if you disagree and we can discuss further

**Comment by vbarzokas** [comment]
@elnyry Is correct here, the expected behaviour is to see error code **3201** and internally we have the bug MOWDEV-4466 for this case.
I have created [this PR](https://circleci.com/gh/mojaloop/account-lookup-service/3926) in order to cover the special case of the Mowali implementation which uses mojaloop/als-oracle-pathfinder and currently returns 404.

**Comment by elnyry** [comment]
@vbarzokas @IvtVasquez if you have the desired behavior here after Vassilis's PR, you may close it. Thanks..
