### ISSUE TITLE
PCI DSS - Responsibility Matrix, Gap Analysis & Standard Baseline for Requirement 4 : Encrypt transmission of cardholder data across open, public networks

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1350]
@godfreykutumela commented on [Thu May 07 2020](https://github.com/mojaloop/mojaloop/issues/286)

## **Goal**:
Create a responsibility matrix, perform a Gap Analysis ( As-Is and To be) for Requirement 4 : Encrypt transmission of cardholder data across open, public networks and provide a standard baseline.

**Tasks**:
- [ ] Create a template [ @godfreykutumela ]
- [ ] Complete the responsibility matrix [ @godfreykutumela ]
- [ ] Perform an assessment (As-Is) [ @godfreykutumela ]
- [ ] Recommendations (To-Be) [ @godfreykutumela ]
- [ ] Compile an overall report with a compliance baseline [ @godfreykutumela ]

**Acceptance Criteria**:
- [ ] Responsibility Matrix
- [ ] As-Is assessment report
- [ ] To-be report with recommendations
- [ ] Completed compliance baseline report

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by elnyry** [comment]
@godfreykutumela - two thoughts on this one.
1. First I think we need to define what the equivalent of "card holder data" is in the Mojaloop world and the FSPIOP API
2. This was attempted initially when the FSPIOP API was being standardized - to use encrypted messages across FSPs or between FSPs and a Switch, but it had to be shelved immediately because there is no scope for Schema Validation anymore at the ml-api-adapter or the API Gateway level, as all messages will be just strings / binary data.

In light of this, I think we need to re-assess this requirement and adherence to it in the context of Mojaloop.

**Comment by godfreykutumela** [comment]
@elnyry Thanks for this input, much appreciated feedback on this initiative. 

1. On the frist point of equating card holder data to something else within the Mojaloop eco system, that's something I attemped before tackling this initiative and unfortunately that but fell short due to unique nature of overall card based eco system - What matters is not only the PAM details but how it is used across the eco system. I tried picking up things like MSISDN or Merchant ID but use cases for those are not similar at all to card data ones so that as well derailed plans pretty quickly. The other challenge here is that fact that PCI DSS addresses more operational issues than design and implementation issues where Mojaloop scope is mainly focused so this effort is really meant to mostly benefit the implementer's prepared to connect their existing card based system to Mojaloop Hub or even introducing the card related use case within the hub.

Mojaloop can benefits from implementing the PCI Software Security Framework which more generic  for developing a secure payment software which is expected to hold card data. This is the standard that software development partners in the card eco system like POS provider limit themselves to. This is in our plans for the next 2 PI's starting from PI 11 to 12.

2. Second point, I am just stretching our compliance to this requirement a bit far to cover both network and presentation level security but actually the standard is just limited to network layer. As for encryption of API messages I would like us to first explore the options of doing at the API Gateway level so my question there is weather we see API Gateway as one core OSS components or not? This is one of major requirement of using an API Gateway to protect data so if can't get working sucessfully then our security use case for an API Gateway is limited mainly to identity and authentication management - I am open for thoughts here and thanks getting me upto speed with what was attempted before on this area.

The brief from Miller was just baseline ourselves against a reputable standard such as PCI DSS focusing mainly on the non-card data security requirements of the standard.

**Comment by elnyry** [comment]
Thanks for the detailed response @godfreykutumela .. Agree on #1 and will discuss more no one of the work-stream calls.

On #2, we can create a new task / Epic focusing on the API Gateway as it offers more controls. But the intent in not being prescriptive is to allow implementers some leeway to choose an API Gateway that they prefer, instead of us here creating that dependency / binding (though a reference implementation with WSO2 was done and demonstrated).

However, Gateway or not, we need to make a decision regarding encryption of in-flight messages ( as you indicated is a stretched requirement / goal) and assess the implications.

**Comment by godfreykutumela** [comment]
Noted thanks @elnyry.

1. We can touch base it in our next call.
2. I agree, we have to give it a special focus maybe as work stream on its own with various epics and end to end rest API secuity can be ones. It was on the code quality work stream epics for PI 8 if you remember and our recommendation was exactly the same that we treat it as a separate work stream and everyone to participate to towards a joint decision.

**Comment by godfreykutumela** [comment]
Ready for team review.
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 4 Report - July 2020 v1.0 Final.xlsx](https://github.com/mojaloop/project/files/4701842/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.4.Report.-.July.2020.v1.0.Final.xlsx)
