### ISSUE TITLE
Investigate Miro - GitHub Integration

### ISSUE THREAD

**Issue by ramakrishnan-sankar** [mojaloop/project#1483]
In preparation for PI-11, investigate Miro-GitHub Integration so as to save time for the team when Epics/Stories have to be transferred from Miro to GitHub.

**Comment by ramakrishnan-sankar** [comment]
Sam explored and reported Integration with GitHub from Miro doesn't exist.  The Issue is to be closed.

**Comment by kjw000** [comment]
we do use Miro for PI planning.
Please review our PI 11 board: https://miro.com/welcomeonboard/H0L4OZWKUzoej8JlCFNdsUxRzD0HrUqPK2yHLcDi1oBvfzzfrqoJiUgJDUwS1kxa

**Comment by elnyry-sam-k** [comment]
@kjw000 - this investigation was to find out if we can automate creation of Epics / stories based on the cards we use on the Miro board so that it will save effort.

However, what I found was that integration from GitHub -> Miro is available but so far, couldn't find anything for what we need, i.e., Miro -> GitHub

**Comment by kjw000** [comment]
thanks for the follow-up
