### ISSUE TITLE
Separation of participant entity into meta and position/account

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1855]
## **Goal**:
`As a ` developer
`I want to` separate the participant data structure into finer grained entities, that at least separates the position/accouts from the rest of the participant metadata. 
`so that` the system only updates the position/account data and not the whole participant data structure on each position update.

**Acceptance Criteria**:
- [ ] TBD

The carved out account should be the individual account and not the list of accounts of a participant. 
Participant:
- Accounts (list);

Account entity:
- participant id;
- currency id;
- account id (relative to the participant);
- virtual partition id;
- limit (position)

**Complexity**: <Medium> > A short comment to remind the reason for the rating
**Uncertainty**: <Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
After some thinking the separation of the participant, and doing some research.

Based on the Reliable Notification effort and the current PoC implementation, we would like to pass the notification metadata (i.e. end-points) as part of the position change events. <-- This is a result of wanting to change the Notification “Engine” to a stateless processor. I.e. it has no dependency other than the event-message that it received to successfully process the notification.

That means that the participant handler will need to have access to both the accounts for a participant and also the end-point information.

I am strongly leaning towards the use of Hash Sets for the separation of participants  for a couple of reasons:
1. Its a really effective way to retrieve subsets of an object efficiently
2. Same holds true for making updates to an object
3. Its considered best practice from a Redis perspective, and its discouraged that one does not “pollute” the main key space --> ref: https://redis.io/topics/memory-optimization
4. We have a limit to the numbers of Keys that Redis can store/manage, using a Hash Sets will ensure that we reduce the number of keys to one for an object. In our case, we at least have a key-space saving of 50%!!
5. It offers the best use of memory since hash sets are very good as optimising the memory footprint for an object
6. Its really hard to manage objects that need to expire <-- this shouldn’t be an issue for participants but included it here for completeness.
