### ISSUE TITLE
SDK Bulk - If the discovery is rejected by payeefsp, the global state is not updating to "COMPLETED"

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#2979]
**Summary**:
TC-BP1 - 
TC-BP2
TC-BP6

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by PaulGregoryBaker** [comment]
TC-BP1 - test passing
TC-BP2 - test passing
TC-BP6 - getting 2 PUT callbacks instead of 1 - final state should be AGREEMENT_COMPLETED, but not getting any PUT response back - missing implementation - #2982 all other asserts passing

The outstanding item is capture in #2982  - so will close this issue
