### ISSUE TITLE
[rep-hub-bop-api-svc] CENTRAL_LEDGER_DB_URL env conf does not support special characters

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3267]
**Summary**:

Bof `reporting-hub-bop-api-svc` service does not support special characters when configuring the username & password for CENTRAL_LEDGER_DB_URL env conf.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**

The `reporting-hub-bop-api-svc` service should support special character on both the username and password when setting the CENTRAL_LEDGER_DB_URL env variable

**Pull Requests**
- [x] https://github.com/mojaloop/reporting-hub-bop-api-svc/pull/15

**Specifications**
  - Component (if known): reporting-hub-bop-api-svc
  - Version: v1.0.31
  - Platform:
  - Subsystem:
  - Type of testing: n/a
  - Bug found/raised by: @dfry 

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3267?planning-poker) with Zenhub @mdebarros @vijayg10 @PaulGregoryBaker

**Comment by vijayg10** [comment]
A new version of the service is released as part of this story https://github.com/mojaloop/reporting-hub-bop-api-svc/releases/tag/v2.0.0
Since its a breaking change due to configuration environment variable changes, we need to update the helm chart with the new configuration parameters.
There should be a followup story to cover the helm chart and IaC changes.
