### ISSUE TITLE
Add scenario in test to not settle a batch in dispute

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3289]
Add a domain unit test to ensure a batch that is in `DISPUTED` state cannot be settled.

# Scenario
1. Create transfer (which will be allocated to `batch A`)
2. Create a transfer under another model which will create `batch B`
3. Create `settlement matrix A` that includes batches A and B
4. Dispute `batch A`
5. Settle `settlement matrix A`
6. Test to ensure only batch B was settled and not batch A

# Location
https://github.com/mojaloop/settlements-bc/blob/main/packages/domain-lib/test/unit/index.test.ts

**Comment by myo-min-htet** [comment]
Hi @koekiebox 

1. According to above the scenario, in the requirement Number 3
I got two batches in a Matrix, and it asked me to dispute a batch in that Matrix. 
It is not possible according to the design in Admin UI because the batches are not able to select.
So, I want to know about the real logic that Is it possible to Dispute or Close or settle specific batch in a matrix?
And also, there is no function to dispute Batch. I found only disputeMatrix function.

2. Is it possible to create multiple matrixes for same batches because currently we can create multiple matrixes for same batches?

**Comment by koekiebox** [comment]
@myo-min-htet 
1. Ok. I would work from the `domain` tests that reside in https://github.com/mojaloop/settlements-bc/blob/main/packages/domain-lib/test/unit/index.test.ts
Step 3 is possible for both `DYNAMIC` and `STATIC` matrixes.
You are only able to execute actions (close/settle/dispute) via a matrix, not through the batches directly.
You are able to close/dispute batches (via a matrix) as long as the batch is not settled. Once a batch is settled, it is final.

There is however a new status being introduced (`AWAITING_SETTLEMENT`) which is currently wip.
Please have a look at the following document for background and explanation:
https://github.com/mojaloop/mojaloop-specification/issues/117#issuecomment-1480797650

2. Yes, but only a single matrix may settle a batch. Please also read about `AWAITING_SETTLEMENT`

**Comment by myo-min-htet** [comment]
@koekiebox , I have created a PR for this. Could you please check and guide me if you see something.
Please see the following for the PR.
https://github.com/mojaloop/settlements-bc/pull/9

**Comment by koekiebox** [comment]
@myo-min-htet I had a look. Thank you, it is looking good! 
I added some comments and explanations in the following commit:
https://github.com/mojaloop/settlements-bc/pull/9/commits/69c08f70547e541c2cbb1065b109f59724f4442e

Please do a `pull` on the branch

**Comment by myo-min-htet** [comment]
@koekiebox ,
Hi Jason, please let me close this item since the PR already merged.
