### ISSUE TITLE
As a developer I would like to Refactor the Settlements table for Big Data Analytics and Reporting in order to determine if it can be implemented to meet the HA, scalability and performance criteria

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#37]
**Goal**:

**Tasks**:
Performance activities:
- [ ] 

**Acceptance Criteria**:
- [ ] 

**Dependencies**:
- None currently

**Comment by HenkKodde** [comment]
This would require information of the current phase of a current single transaction within the current environment. Big question is how and for what are 'Big Data' is to be utilized. Final state, time to achieve final state or do we consider Queued and Pending request as well. Running queries on active data on tables could potentially have a performance impact on the current request. The MIS information could be 'out of date' a couple of seconds later. 
My view on the above - Big data can be viewed from two sided (analytics are used to assist the current environment statistics in order to insure stability and attain stability, or  complement and improve business productivity and utilize the information to improve productivity. Fundamentally these are 2 different concepts (ensure a stable system(using current information) or grow the business(trend annalist -(historical information to establish potential opportunities and address gaps in the current solution/offerings)?
