### ISSUE TITLE
Perform One Round of QA Testing with New Currency Integration on vNext Portal

### ISSUE THREAD

**Issue by myo-min-htet** [mojaloop/project#3893]
## User Story
As a hub operator, we'd like to add new currency based on the scheme needs.
### Acceptance Criteria
  - Newly added currency should be displayed in the Admin portal dropdown
  - The UI should allow the creation of necessary accounts with new currencies, such as settlement account and position account
  - It should facilitate the transactions with new currencies
  - The report accurately displays the transfers and amounts in the new currency
  - After finalizing the settlement, the amount should be updated in both the settlement account and the position account for the new currency

**Comment by smthitsaworks** [comment]
one finding is that though Dev added new currency in the backend, on the UI screen like creating position account and liquidity account screens, the new currency cannot be automatically included. Dev manually added the new currency in the dropdown list since there is no connection between the currency dropdown list and currency config in the backend. That's why whenever the new currencies are added, manual job such as adding new currencies to the dropdown list is mandatory.
