### ISSUE TITLE
Display Error Reason for Insufficient Liquidity Transfer at Transfer Page

### ISSUE THREAD

**Issue by zinzinnyohlaing-tw** [mojaloop/project#3912]
I would like to know the error reason at the Transfers page if the transactions failed due to insufficient liquidity transfer, so that I can quickly address and resolve any issues.

**Acceptance Criteria**

1. The level one support people should be aware of the error reason for transfer failures due to insufficient liquidity within the portal.
2. The error reason should be displayed in the "Error Reason" column on the Transfer page.
3. The error messages displayed in both the admin portal and the Kibana log should be the same, following the API definition of the Open API for FSP Interoperability (https://github.com/mojaloop/interop-apis-bc/blob/main/packages/fspiop-utils-lib/src/enums.ts)

Doesn't include error reason at Transfer Page
<img width="1129" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5nQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--418dbe9842404d6398b1a722dfd36ac1409c0210/image.png" alt="image.png" />

Include error message at Kibana log
<img width="1360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTNnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f81b359ad8c8d8db99f7998d60a654dc24820015/image.png" alt="image.png" />

**Comment by ei-nghon-phoo** [comment]
for acceptance criteria 1 and 2: it will be fixed with seperate ticket. 
for AC 3: Ensuring that string values are exactly identical requires significant effort and offers minimal benefit, given that the strings convey the same meaning. Errors in the admin portal and Kibana logs will be internal BC errors, whereas errors related to the FSPIOP API will link to the DFSP core connector and will utilize FSPIOP error codes.
