### ISSUE TITLE
Failure in P2P - Transfer Prepare - Payee DFSP Notification is not sent

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#403]
When I run the P2P goldenpath from Cucumber pointing to the Mojaloop env, transfers are failing. From cucumber logs it is shown that the request is sent to the switch. But the payeefsp simulator did not receive the corresponding transfer-prepare request. In the ml-api-adapter logs, I see that the original request came through but notification is not sent to the payeefsp to respond.

**Comment by sri-miriyala** [comment]
Miguel provided a hotfix on this. 
I retested p2p golden path from Cucumber against ML interop switch and still end to end transfers are failing. What I noticed is that the transfer request is reaching the payeefsp from the switch and I can see that the payeefsp is responding back with the fulfilment response. But, I’m not able to see the final transfer response coming to the payerfsp.

**Comment by sri-miriyala** [comment]
Re-tested end-end transfers. Now seeing that payee fsp is not receiving transfer notification. Yesterday this was working, but now not working.

**Comment by mdebarros** [comment]
Fixed with the following snapshot release: https://github.com/mojaloop/ml-api-adapter/releases/tag/v3.3.2-snapshot

Waiting for verification by @sri-miriyala on this bug and on https://github.com/mojaloop/ml-api-adapter/issues/31.

But did log the following issues:

- https://github.com/mojaloop/central-ledger/issues/121
- https://github.com/mojaloop/central-ledger/issues/122
- https://github.com/mojaloop/central-ledger/issues/123

**Comment by sri-miriyala** [comment]
This is working from Cucumber, which is good enough for continue testing further. Hence closed.
Thanks much Miguel.
