### ISSUE TITLE
[80] Transfer request with expiration date from the past

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#426]
If I submit a transfer with expiration value before current date, the Switch should reject the transfer with error message indicating the field that caused the validation to fail and the reason for the failure. Instead, currently a "Generic Validation" error message is being returned.

**Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/141
- [x] https://github.com/mojaloop/ml-api-adapter/pull/51

**Comment by elnyry** [comment]
Thanks Sri, lets take care of this in the Post-PI3 sprints

**Comment by ggrg** [comment]
We would like to get more information whether this validation should be made by ml-api-adapter or it should be passed through to central-ledger and validated there with logging the request.

**Comment by sri-miriyala** [comment]
Georgi, I'm assuming this is not a question for me as I do not have much insight into internal architecture.

**Comment by elnyry** [comment]
Thank you Sri and Georgi - this is a good question and we can discuss it with the team; personally I feel it should get rejected at the ml-api-adapter

The advantage is that we save cycles in the central services by avoiding processing since this doesn't need any information from the central services.. but we need a balance as well not to put too much logic for validation in the ml-api-adapter itself..

I feel for this one, we should be able to handle it in ml-api-adapter and respond with a better message as Sri suggested.

**Comment by sri-miriyala** [comment]
Team, pls assign the task to me once the fix is available for testing. I will test and close the bugs accordingly.

**Comment by sri-miriyala** [comment]
@ggrg I know that you made code fixes for that. Any idea when that will be deployed?

**Comment by elnyry** [comment]
Great

**Comment by elnyry** [comment]
But this is not an ideal way to solve this - an error code most likely should be tied to a single error description; In the future we may have to come up with a new errorCode, description pair.. Customizing errorDescriptions takes away the capability to implement error handling in a generic way.. 

But I think this is OK for now
