### ISSUE TITLE
Fulfillment Failure - Invalid error message in PayeeFSP

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#436]
If the fulfillment response received from PayeeFSP failed for whatever reason, the expected behavior is that error code/error message should be sent to both PayerFSP and PayeeFSP at the error endpoint. Currently the error message is not being sent correctly. That is one issue. Other issue is that PayerFSP is not receiving the error message.

Received error in Payeefsp /transfers/{transferId}/error: {"errorInformation":{"errorCode":3106,"errorDescription":"Modified request"}}

**Comment by elnyry** [comment]
Hi Sri, this needs more discussion.

This is not as straight forward as it seems: If there is a failure in fulfilment, there is no need to inform the Payer (it will get timed-out eventually - when both parties should be informed), because it may be a failure because that fulfilment was invalid or some other validation failed or an internal error may have happened - In this case only the Payee needs to be informed.

**Comment by sri-miriyala** [comment]
Sorry Sam, I realized that I was posting in a wrong thread. Let's comment here for easy tracking.

**Comment by elnyry** [comment]
The error message - code, description need to be corrected, but as I mentioned in the other place you asked this, not informing the Payer at this point is fine, since it is NOT a Rejection but a validation failure.. But, I'm open for discussion on this, may be we can have a meeting to discuss/triage all the open bugs nest week

**Comment by sri-miriyala** [comment]
Yes, Sam. I agree with your analysis that only payeefsp should receive the notification for invalid fulfilments and upon timeout both FSPs get notified. 
In this case, I could see the transferStatechange when it timedout eventually. 
<img width="595" alt="screen shot 2018-09-06 at 11 01 48 pm" src="https://user-images.githubusercontent.com/38143240/45196205-27723700-b229-11e8-8ad3-0a2c49222d19.png">
But I do not see any activity between RESERVED and RESERVED-TIMEOUT as there could be no. of invalid fulfilments between payeefsp and Switch, for which only the payeefsp gets notified.

**Comment by sri-miriyala** [comment]
Is this activity captured anywhere in DB? If so, where?

**Comment by elnyry** [comment]
Hi Sri, the trace that you posted looks pretty good, is expected and I'm happy to see it. The transferState shouldn't/wouldn't change because of requests where validation fails.

However, one place where you can see something about these invalid requests is in this table - transferDuplcateCheck (You can check using the transferId and should be able see the createdDate, hash and there will be an associated transferFulfilmentId in the transferFulfilment table - which is generated for every incoming fulfilment request and there should be an isValid flag which helps identify whether that Fulfilment with transferFulfilmentId is valid or not).

Please let me know if you have any questions

**Comment by sri-miriyala** [comment]
I agree too....Initially I was thinking that the transfer will be aborted, but yeah, it makes sense that the Payee should have an opportunity to correct themselves till timeout on validation failures. I do see that the Payee is getting notified, but the error message is not right.

@elnyry let me know if you want me to close this bug and create a new one for the error message description.

**Comment by elnyry** [comment]
Yes please.. Thanks Sri, and that new bug would be of a lesser priority since its just the error message description.

**Comment by elnyry** [comment]
Also one more note about this error message - "Received error in Payeefsp /transfers/{transferId}/error: {"errorInformation":{"errorCode":3106,"errorDescription":"Modified request"}}"

If a message with a transferId has a wrong fulfilment then the above message is justified.. There may be other scenarios where it is not (but in this instance, it is fine, if the fulfilment is wrong).

**Comment by sri-miriyala** [comment]
Not sure if I agree with this errorCode/errorDescription based on reading the spec. So below is the detail for the errorCode being returned right now, which is not appropriate I think.

3106 | Modified request | Request with the same ID has   previously been processed in which the parameters are not the same.

What I am talking about here is not even a duplicate request. In the first attempt, there is a validation failure on fulfillment. So I think the below 2 errorCodes might be appropriate:


3100 | Generic validation error | Generic validation error to be used   in order not to disclose information that may be considered private.

3101 | Malformed syntax | Format of the parameter is not valid.   For example, amount set to 5.ABC.   The error description field should specify which information element is   erroneous.

In this case, the format is OK, its just that the content is invalid that led to the validation failure. So I think 3100 makes more sense. Although, if I look from a consumer standpoint, I would like to know which field in my response caused the validation failure so that I can correct myself.  In this specific case, if the errorMessage from switch tells me that the validation failed because of "fulfillment" being invalid, that will be more helpful in correcting that. Instead if all I get a "Generic validation error", not sure if it adds much value to the client trying to re-send a correct response.

**Comment by elnyry** [comment]
Thank you Sri.

As you seem to agree, 3101 is not an option for this. The options we have are 3100 and 3106.

For 3106 - The reason I said this can be justified is because this is the closest we have with the current options, because for the same transferId we should've received a different (valid) fulfilment but received a wrong one, hence a _modified request_ message is ok, though it is arguable.

If you say 3100 is better, I'm ok with that as well. 

Please note that while specific errors and hints while helpful during debugging, QA are not desirable and sometimes outright misplaced in production. The consumers of this error, as you suggested are FSPs (and not an end-user such as payer or payee) who should've implemented the API as per the spec (in conjunction with Scheme rules) and being part of a Financial system it may be best to use 3100 for security, fraud prevention and related reasons.

**Comment by sri-miriyala** [comment]
Thanks Sam for your comments. I think we need perspective from others too as we seem to have divergent views. To me, 3106 seems to be more applicable for duplicates.
 
My opinion is different from your comment on sending specific fields as part of error description being more related to QA and a security threat. Especially when the spec says "Format of the parameter is not valid. For example, amount set to 5.ABC. **The error description field should specify which information element is erroneous**."
May be we can take input from Security team if this poses a security issue. Also we are not specifying actual values, instead only metadata(field names).
 
But to proceed further on this issue, I am OK with 3100 too.

**Comment by elnyry** [comment]
When the spec says - "_Format of the parameter is not valid. For example, amount set to 5.ABC. The error description field should specify which information element is erroneous._", it is about Schema validation issues where the **format** is not valid. It is about Malformed syntax as it clearly states..

**Comment by sri-miriyala** [comment]
Yes. The reason I included that text from the spec is to highlight the fact that the spec says its OK to include the information elements(just the field names, not the values) in the error messages. As you mentioned before that including information elements poses security issues, I wanted to bring that to your attention. 

We already ruled out that this use-case does not fall under Malformed Syntax error code (3101) and  3106( which I feel is for duplicates). Let's proceed with 3100 and Generic validation error as the spec says.

**Comment by elnyry** [comment]
Hi Sri, It is OK to give information regarding failures for failures in schema validation but not for others types of validation that happen internally (not at the schema validation level that happens in the ml-api-adapter)

**Comment by elnyry** [comment]
Merged to develop.. Can be verified when the next version is deployed.

**Comment by elnyry** [comment]
Deployed as of right now - needs to be verified. Thank you

**Comment by sri-miriyala** [comment]
The conclusion of this story is, only payee receives error msg upon invalid fulfilment from payee via transfer fufil request before the timeout period. 
This has been tested and as expected payee receiving error msg "Generic validation Error".
Screen shot:
<img width="1424" alt="screen shot 2018-10-03 at 1 38 54 pm" src="https://user-images.githubusercontent.com/38143240/46428499-22ae7f00-c712-11e8-956c-7fb16f4b3a40.png">

Hence closed.
