### ISSUE TITLE
Invalid response - GET Settlements using Settlement, Participant and Account ID's

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#491]
Priority: Medium
Env: ML AWS 
Version: Central Settlements 3.7.0
Tool: Postman
API : Settlements
Endpoint: GET /settlement by settlementParticipantAccount

Description:
Payerfsp having participant Id 1 & Account Id (participant Currency Id) 2 respectively.
Payeefsp having participant Id 2 & Account Id (participant Currency Id)  2 respectively.
Both have transactions in settlement ID '1'

When I query against GET settlement by providing settlement Id =1, participant Id =1 and Account Id =1, I'm getting the response back as expected which are the details of payerfsp with its corresponding account Id of 1.
But, When I provide settlement Id =1, participant Id=2 and account Id =1, I'm supposed to get an error msg as participant 2 is not associated with account Id 1 and vice versa. But I noticed a response back with payerfsp details as if the request is for participant id 1 whose account id is 1.

So, irrespective of the participant Id's, I'm getting response based on account Id's. Which is a bug.

Screenshot: Correct response for participant Id "1" and Account Id "1"
<img width="653" alt="screen shot 2018-10-04 at 1 48 03 pm" src="https://user-images.githubusercontent.com/38143240/46493435-56ef7180-c7de-11e8-8036-28a116542020.png">

Invaid response for participant Id "2" and account Id "1"
<img width="843" alt="screen shot 2018-10-04 at 10 20 56 am" src="https://user-images.githubusercontent.com/38143240/46493455-67075100-c7de-11e8-9111-fd4ae9d81951.png">

Expected result:
Should return an error msg saying the participant Id and Account Id are not matching.

**Pull Requests**:
- [ ] https://github.com/mojaloop/central-settlement/pull/49

**Comment by elnyry** [comment]
hi Georgi, Sri - I agree that we shouldn’t return an error but can we return data only that only matches all the query params ?

**Comment by ggrg** [comment]
Following are the findings when investigating the reported issue:
1. In order to get to the point of issuing the GET I needed to change the demo scripts to work with the latest versions of ml-api-adapter and central-ledger. These changes were pushed to [this branch](https://github.com/mojaloop/central-settlement/tree/bugfix/491InvalidResponseForGetSettlementBySettlementParticipantAccount). Please checkout code from it, when resuming work on this.
2. It is bigger than a simple fix. getByIdParticipantAccount method that we might find [here](https://github.com/mojaloop/central-settlement/blob/develop/src/domain/settlement/index.js#L218) is in it initial state from the very first commit, and as you may observe from the link above - for the cases where **!participantAndAccountMatched** or where **!settlementParticipantCurrencyList**, we have
```throw new Error('TODO')```
which implies implementing a feature that was never implemented before.
3. Actually, the check ```await SettlementModel.checkParticipantAccountExists``` on line 229 is wrong for two reasons:
  **a/** it returns an array, because .first() is not used in the knex query
  **b/** at time of implementation, we didn't have SETTLEMENT accounts for the participants, thus that check would also work if settlement account id is provided against a particular participant.
4. If we're not going to return error for empty sets, then we actually need to get rid of the above mentioned check in 3 and rework the entire method, so there are no checks but a knex query that takes all parameters in count and returns result accordingly. After saying this, it would probably be easier to start this method from scratch. Also, for the effort needed, please keep in mind that the corresponding unit tests also need to be refactored.
5. Last, let's say that we get to point where **/settlements/1/participants/2/accounts/1** returns the desired output and no other account ids work with settlement id 1 and participant id 2. The next question to be answered before reworking the endpoint is wether account id is mandatory part of the query, or another endpoint should be exposed to also return the result of **/settlements/1/participants/2**, which is currently not implemented at all (HTTP Status: 404 Not Found)

**Comment by elnyry** [comment]
Thanks Georgi. Lets revisit this after key features are delievered (508, 506, 507, 517, 518)

**Comment by elnyry** [comment]
To be verified in 4.1 Sprint

**Comment by sri-miriyala** [comment]
Retested and is working as expected. Tested with valid fspId and position Id combinations (As the new settlement features changed, we are using position acct Id to settle instead of settlement account ID).
Tested with invalid fspId and position acct ID, is giving error msg like the below.
<img width="1421" alt="screen shot 2018-11-27 at 1 49 13 pm" src="https://user-images.githubusercontent.com/38143240/49105591-fbc28400-f24e-11e8-9898-16306c5204e4.png">

Valid input:
<img width="1430" alt="screen shot 2018-11-27 at 1 49 39 pm" src="https://user-images.githubusercontent.com/38143240/49105602-0250fb80-f24f-11e8-8849-ca3506a20da6.png">

Also tested for 404- not found by missing account ID / settlement ID in the URI

Hence closed.
