### ISSUE TITLE
Failed to create a participant with currency "XOF"

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#527]
Priority: HIGHEST
Env : ML AWS 
version: ML 3.8.3
End point: Admin API , POST /participants

**Description:** Failed to create a participant with currency "XOF"
**Expected Behavior:**
1. When I try to create a participant with Currency "XOF" using Admin API, POST /participants . 
2.The participant with given currency "XOF" should be created with response code 201-created.

**Actual behavior:**
1. I tried creating a participant "payerfsp1" with currency "XOF" using below request:
REQUEST:
curl -X POST \
http://test-central-ledger.mojaloop.live/admin/participants \
-H 'Cache-Control: no-cache' \
-H 'Content-Type: application/json' \
-H 'Postman-Token: b01156dc-866c-499e-b74f-065f1dfc490b' \
-d '

{ "name": "payerfsp1", "currency": "XOF" }
'

2. I got the below response: **(FAILED)**

{ "id": "BadRequestError", "message": "child \"currency\" fails because [currency must be one of [ALL, AFN, ARS, AWG, AUD, AZN, BSD, BBD, BYN, BZD, BMD, BOB, BAM, BWP, BGN, BRL, BND, KHR, CAD, KYD, CLP, CNY, COP, CRC, HRK, CUP, CZK, DKK, DOP, XCD, EGP, SVC, EUR, FKP, FJD, GHS, GIP, GTQ, GGP, GYD, HNL, HKD, HUF, ISK, INR, IDR, IRR, IMP, ILS, JMD, JPY, JEP, KZT, KPW, KRW, KGS, LAK, LBP, LRD, MKD, MYR, MUR, MXN, MNT, MZN, NAD, NPR, ANG, NZD, NIO, NGN, NOK, OMR, PKR, PAB, PYG, PEN, PHP, PLN, QAR, RON, RUB, SHP, SAR, RSD, SCR, SGD, SBD, SOS, ZAR, LKR, SEK, CHF, SRD, SYP, TWD, THB, TTD, TRY, TVD, UAH, GBP, USD, UYU, UZS, VEF, VND, YER, ZWD]]" }
Screenshot:
<img width="776" alt="xof-notcreated" src="https://user-images.githubusercontent.com/38143240/47872493-1850d500-dde5-11e8-9fe2-5a6568b57af7.png">

What I noticed here is, in ML 3.8.3 implementation, XOF is not listed in the acceptable currencies list.
But when I see Swagger Spec, it is listed there. Apart from XOF, some other currencies (approx 8) also missing from the implementation.

Below is the Screenshot from Swagger spec:
<img width="632" alt="currencies - swagger" src="https://user-images.githubusercontent.com/38143240/47872507-2141a680-dde5-11e8-869a-f81571bd6c27.png">

Created By : Sri

**Comment by ggrg** [comment]
Taks:
- [x] Investigate issue -> Joi validation array differs the db seeds file
- [x] Alter code for single source of truth -> seeds file
- [x] Compare seeds file with [fspiop-rest-v1.0-OpenAPI](https://github.com/mojaloop/mojaloop-specification/blob/develop/Supporting%20Files/fspiop-rest-v1.0-OpenAPI.yaml)
- [x] Add all missing currencies to seeds: AFN, AOA, BAM, CUC, GGP, IMP, JEP, SPL, TVD, ZMW, ZWD
- [x] Extract list of currencies that are extra to the spec: AFA, AOR, EEK, XAU, XFO, LVL, LTL, XPD, XPT, XAG, XFU, ZMK, ZWN, ZWR, ZWL
- [x] Enforce currency validator for endpoint POST /participants/{name}/accounts
- [x] Test endpoints with valid and invalid currencies
- [x] Sort the currency list in alphabetical order in order to produce more readable Joi validation failure message
- [x] Change misleading error message to: _Hub account has already been registered._
- [x] Investigate when/how bug was introduced
- [x] Create PR: https://github.com/mojaloop/central-ledger/pull/197

**Comment by sri-miriyala** [comment]
Hi team, with new deployment v3.9.0 from ML, this issue has been resolved and I'm able to create a participant with currency "XOF"
REQUEST :
curl -X POST \
http://test-central-ledger.mojaloop.live/admin/participants \
-H 'Content-Type: application/json' \
-H 'Postman-Token: 7f4bed48-6889-4d2b-a29b-04a01c8c0eea' \
-H 'cache-control: no-cache' \
-d '

{ "name": "testfsp1", "currency": "XOF" }

RESPONSE:
<img width="822" alt="screen shot 2018-11-08 at 7 42 47 am" src="https://user-images.githubusercontent.com/38143240/48199735-0b733a80-e32b-11e8-87dd-8fc8ea7b1406.png">

Hence the issue is closed.
