### ISSUE TITLE
Integration-test-runner unexpected operator error [central-settlement]

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#643]
**Summary**:

The integration test runner throws an error `./test/integration-runner.sh: 348: [: 0: unexpected operator` as per the following excert:

```BASH
Integration tests are starting
Running central-settlement-int Test command: mkdir -p test/results; tape 'test/integration/**/*.test.js' | tap-xunit > test/results/tape-integration.xml
Test exited with result code.... 0 ...
Displaying test logs
Copy results to local directory
./test/integration-runner.sh: 348: [: 0: unexpected operator
Integration tests failed...exiting
Test environment logs...
Kafka is shutting down kafka-int
simulator-int environment is shutting down
central-ledger-int environment is shutting down
ml-api-adapter-int environment is shutting down
db-int environment is shutting down
central-settlement-int environment is shutting down
Deleting test network: integration-test-net
integration-test-net
Integration tests exited with code: 0
```
**Central-settlement related update**: The following [Pull Request](https://github.com/mojaloop/central-settlement/pull/72) was merged with integration tests disabled for central-settlement. As a part of resolving this issue, central-settlement integration testing needs to be re-enabled and successful.
- [x] https://github.com/mojaloop/central-settlement/pull/73

**Source**: https://circleci.com/gh/mojaloop/central-settlement/1266?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known): CircleCI for ML-API-Adapter & Central-Ledger, Central-Settlement
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened: Low
- Priority when opened: Low

**Comment by elnyry** [comment]
Next steps:

enhance integration test runnners:
1. do not run helper containers with --rm (as useful log information will be lost for debugging purposes)
2. add additional checks during the "is_up()" functions for helper container startups to check the container status via `docker inspect`...if the `$(docker inspect -f '{{.State.ExitCode}}' $container_name) != 0`, then exit the loop and print the container log file `docker log $container_name`, and exit the integration test with an error `exit 1`
3. do not have a copy of the integration configs for each helper container, but instead copy the config from the helper containers repo via a curl command. This will ensure that we only have a single config to manage and maintain instead of worrying about maintaining many copies
4. Fix Integration-test-runner unexpected operator error [central-settlement]

**Comment by lewisdaly** [comment]
@elnyry I wonder if this can be part of further discussion on improving the test runners by:
- using `docker-compose` to run all containers in one command instead of spinning up containers with many `docker run` commands
- change the integration runner `.sh` script to a `Makefile` that we can call from CircleCI. I find using make instead of bespoke scripts much easier to control, reproduce and debug. I can dig up some samples of reasonable makefile configs I've written in the past that are less flaky and archaic than pure shell scripts.

**Comment by elnyry** [comment]
Thanks @lewisdaly , I agree about the first point. Would like to discuss the second one separately.

**Comment by ggrg** [comment]
The original issue has been resolved by https://github.com/mojaloop/central-settlement/pull/149 ([link](https://github.com/mojaloop/central-settlement/pull/149/commits/efd0c2f2aafd6fd41add5a5f2c3753b3979b4f20#diff-437bae27bbd4e278fa0044a4730676bd))
