### ISSUE TITLE
Central-services-stream unit tests fail in circleci when all tests are enabled

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#652]
**Summary**:

When all tests are enabled in `central-services-stream/test/kafka/consumer.test.js` and tests are run in **circleci** with node v10.15.1 the following error occurs:
```
# Consumer test Test Consumer::consume poller sync=false, messageAsJson=true - consumer callback with error
2019-02-25T16:41:15.160Z - error: Consumer::onError()[topics='test'] - error test test)
not ok 310 should be equal
  ---
    operator: equal
    expected: 'this is an error rejected'
    actual:   'error test test'
    at: Consumer.c.on.error (/home/circleci/project/test/kafka/consumer.test.js:1551:16)
    stack: |-
      Error: should be equal
```
Error doesn't occur every time, but randomly.
Disabling the test reduced code coverage and we currently have:
```
ERROR: Coverage for branches (89.11%) does not meet per-file (/home/circleci/project/src/kafka/consumer.js)  threshold (90%)
```

**Severity**:
Low

**Priority**:
Medium

**Expected Behavior**

**Steps to Reproduce**
  1. Enable all tests in central-services-stream/test/kafka/consumer.test.js

**Specifications**
  - Component (if known): central-services-stream
  - Version: 5.2.0
  - Platform: circleci
  - Subsystem: N/A
  - Type of testing: manual
  - Bug found/raised by: @ggrg

**Notes**:
- Severity when opened: Low
- Priority when opened: Medium

**Comment by mdebarros** [comment]
We can close this.

We are currently running all unit tests for quite some time. I believe this issue was caused due to an incompatibility of the node version and the node-rdkafka library version at the time.

https://app.circleci.com/insights/github/mojaloop/central-services-stream/workflows/build_and_test/tests?branch=master <-- here is the latest commit to the master branch where all 377 have passed on 2021 July 6th.

**Comment by elnyry-sam-k** [comment]
Thanks @mdebarros
