### ISSUE TITLE
500 http code responded instead of 4xx in Admin API 

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#981]
**Summary**:
Following calls were responding with 500 - internal http code rather than 4xx http

1. Add participant - `POST /participants` - duplicate account
2. `GET /paricipants/xyz` - Not exist
3. Add participant - `POST /participants` - Invalid currency

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**:
Code, Description, httpStatusCode
1. 3000, Generic client error, 400
2. 3200, Generic ID not found, 400
3. 3101, Malformed syntax, 400

**Steps to Reproduce**

--------------------------------
GET /participants/xyz - participant that does not exist

Curl code:
```
curl -X GET \
  http://dev1-central-ledger.mojaloop.live/participants/xyz \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer {{BEARER_TOKEN}}' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'FSPIOP-Source: payerfsp' \
  -H 'Host: dev1-central-ledger.mojaloop.live' \
  -H 'Postman-Token: bdfdeb1a-080e-4c16-b9cb-249182de635c,1f4eec49-473d-4784-bdd8-fc5de4e2a874' \
  -H 'User-Agent: PostmanRuntime/7.17.1' \
  -H 'cache-control: no-cache'
/participants - with invalid currency
```

--------------------------------
Add participant - POST /participants - Invalid currency

curl Code : 
```
curl -X POST \
  http://dev1-central-ledger.mojaloop.live/participants \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer {{BEARER_TOKEN}}' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 43' \
  -H 'Content-Type: application/json' \
  -H 'FSPIOP-Source: payerfsp' \
  -H 'Host: dev1-central-ledger.mojaloop.live' \
  -H 'Postman-Token: c6ceabb8-1acd-43cc-ad9b-fe4d8e72f882,3c841724-d79f-4c53-9468-fa1256812b32' \
  -H 'User-Agent: PostmanRuntime/7.17.1' \
  -H 'cache-control: no-cache' \
  -d '{
  "name": "payer10",
  "currency": "A#"
}'
```

Expected : ?
Actual Error code : `2001`

-----------------------
Add participant - POST /participants - duplicate account
```
curl -X POST \
  http://dev1-central-ledger.mojaloop.live/participants \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer {{BEARER_TOKEN}}' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 45' \
  -H 'Content-Type: application/json' \
  -H 'FSPIOP-Source: payerfsp' \
  -H 'Host: dev1-central-ledger.mojaloop.live' \
  -H 'Postman-Token: 5e146e31-ae39-4170-b01b-c1dacc701bb0,2ff16736-e8f4-4670-97f6-eb2202438ff7' \
  -H 'User-Agent: PostmanRuntime/7.17.1' \
  -H 'cache-control: no-cache' \
  -d '{
  "name": "payerfsp",
  "currency": "XOF"
}'
```
-----------------

**Specifications**
  - Component (if known): central-ledger
  - Version:
  - Platform: Dev 1
  - Subsystem:
  - Type of testing: 
  - Bug found/raised by: Amar

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Requests
- [ ] ~https://github.com/mojaloop/sdk-standard-components/pull/19~ [@oderayi]
- [x] https://github.com/mojaloop/central-services-error-handling/pull/84 [@ggrg]
- [x] https://github.com/mojaloop/central-ledger/pull/451

**Comment by elnyry** [comment]
Thanks @amarmodus , we'll need to address this..

**Comment by elnyry** [comment]
1. The Mojaloop error codes (enums) that we use from the sdk standard components here: https://github.com/mojaloop/sdk-standard-components/blob/master/src/lib/errors/index.js  I think was drafted taking into account the Mojaloop FSPIOP API.
2. Since this was ‘async’, only the Schema validation errors and others that happen at the ml-api-adapter (or a similar adapter) level need HTTP error response code. The rest that happen during processing are conveyed using callbacks on `/error` endpoints (and so do not need HTTP response codes).
3. For uniformity, I think we decided to use the same data model for error messages in others APIs / services as well, such as central-settlement, ALS admin side, central ledger admin service..
4. The issue with this is that while the ML FSPIOP API is ‘async’, most of the others, in this context the ‘central ledger admin’ service are ‘sync’. So, we still need HTTP response codes for errors even if we use the same data model for response messages.. But since these are not defined, they’re defaulting to  500 and giving ‘internal server error’ on these issues such as FSP not found on admin service doesn’t look right..
5. Without touching the sdk standard components (so that we can leave that for applying on ML FSPIOP API), this needs be addressed, so that we can apply that uniformly across all the synchronous services, probably by extending it / building on top it (but separately)

**Comment by ggrg** [comment]
Currently we use central-services-error-handling as a wrapper for sdk-standard-components and we create and export FSPIOPErrorCodes out of MojaloopSDKError.MojaloopApiErrorCodes. We actually extend those by adding MolajoopTypes @ `central-services-error-handling/src/enums`:
![image](https://user-images.githubusercontent.com/20338055/66840908-77194b00-ef71-11e9-847c-0db60634ade3.png)
![image](https://user-images.githubusercontent.com/20338055/66840950-87c9c100-ef71-11e9-8bc3-d31b4bdca86b.png)
My proposal is to extend `central-services-error-handling/src/enums` so that missing httpStatusCodes are added to FSPIOPErrorCodes (with override, where applicable).
